Document: maxview
Title: Debian maxview Manual
Author: <insert document author here>
Abstract: This manual describes what maxview is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/maxview/maxview.sgml.gz

Format: postscript
Files: /usr/share/doc/maxview/maxview.ps.gz

Format: text
Files: /usr/share/doc/maxview/maxview.text.gz

Format: HTML
Index: /usr/share/doc/maxview/html/index.html
Files: /usr/share/doc/maxview/html/*.html
