Document: paperman
Title: Debian paperman Manual
Author: Simon Glass <sjg@chromium.org>
Abstract: This manual describes what paperman is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paperman/paperman.sgml.gz

Format: postscript
Files: /usr/share/doc/paperman/paperman.ps.gz

Format: text
Files: /usr/share/doc/paperman/paperman.text.gz

Format: HTML
Index: /usr/share/doc/paperman/html/index.html
Files: /usr/share/doc/paperman/html/*.html
