#!/bin/bash

# script to build paperman for all available distributions and architectures

#set -e

RESULTDIR=../release
ALLDIR=$RESULTDIR/all
LOGDIR=../release/log
[ -d $RESULTDIR ] || mkdir $RESULTDIR
[ -d $LOGDIR ] || mkdir $LOGDIR

# the pbuilder runs as nobody and needs write access
chmod 777 $RESULTDIR
mkdir -p $ALLDIR

DISTLIST=$(ls -d /var/cache/pbuilder/*.cow)

./scripts/make_tar

UDISTS="bionic focal jammy noble questing"

# Build paperman for a particular distribution and architecture
# $1: Distribution name, e.g. "bionic", "bookwork"
# $2: Architecture name, e.g. "amd64", "arm64"
doit() {
    local DIST="$1"
    local ARCH="$2"
    VENDOR_VERSION=
    #if [[ "${UDISTS}" == *"${DIST}"* ]]; then
    #    VENDOR_VERSION=ubuntu1
    #fi

    RESULT=$RESULTDIR/$DIST
    mkdir -p $RESULT
    chmod 777 $RESULT

    # Select a special control file if needed
    if [ -f debian/control.${DIST} ]; then
        cp debian/control.${DIST} debian/control
    else
        cp debian/control.in debian/control
    fi

    # Select a special rules file if needed
    if [ -f debian/rules.${DIST} ]; then
        cp debian/rules.${DIST} debian/rules
    else
        cp debian/rules.in debian/rules
    fi
    chmod a+rwx debian/{control,rules}

    # Set up the changelog
    sed s/VENDOR_VERSION/$VENDOR_VERSION/ debian/changelog.in >debian/changelog

    if [ -n "$VENDOR_VERSION" ]; then
        sed -i 's/Maintainer/XSBC-Original-Maintainer/' debian/control
        sed -i '/XSBC/a Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>' debian/control
    fi

    # get version
    VERSION=`grep "^paperman" debian/changelog |head -1 | awk -F "[()]" '{print $2}'`
    echo $DIST $ARCH $VERSION

    LOGFILE=$LOGDIR/$DIST-$ARCH.log
    cmd="sudo ARCH=$ARCH DIST=$DIST pdebuild --pbuilder cowbuilder \
        --buildresult ../release/$DIST -- \
        --basepath /var/cache/pbuilder/base-$DIST-amd64.cow/"
    echo "$cmd" >$LOGFILE
    $cmd >>$LOGFILE

    if [ $? -ne 0 ]; then
	echo "- error: $LOGFILE"
    else
	DEB=$RESULT/paperman_${VERSION}_$ARCH.deb
	sudo chmod a+r $DEB

	# copy into the 'all' directory with a _dist filename
	cp $DEB $ALLDIR/paperman_${VERSION}_${ARCH}_$DIST.deb
    fi

    # Remove the created files
    rm debian/changelog debian/control debian/rules

    # generates
    # -rw-rw-r--  1 sglass sglass       898 2010-11-03 20:51 paperman_0.7-1.diff.gz
    # -rw-r--r--  1 sglass sglass       848 2010-11-03 20:51 paperman_0.7-1.dsc
    # -rw-------  1 nobody nogroup     1464 2010-11-03 20:56 paperman_0.7-1_i386.changes
    # -rw-------  1 nobody nogroup  1159314 2010-11-03 20:56 paperman_0.7-1_i386.deb
}

# For testing individual builds
#doit focal amd64
#exit

for chrootdir in $DISTLIST; do
    DIST=$(basename $chrootdir | cut -d'-' -f2)
    ARCH=$(basename $chrootdir | cut -d'-' -f3)
    ARCH=${ARCH%.cow}
    doit ${DIST} ${ARCH}
done
