#!/bin/bash

# script to build maxview for all available distributions and architectures

#set -e

RESULTDIR=../release
ALLDIR=$RESULTDIR/all
LOGDIR=../release/log
#RESULTDIR=$1
[ -d $RESULTDIR ] || mkdir $RESULTDIR
[ -d $LOGDIR ] || mkdir $LOGDIR

# the pbuilder runs as nobody and needs write access
chmod 777 $RESULTDIR
mkdir -p $ALLDIR

DISTLIST=$(ls -d /var/cache/pbuilder/*.cow)

# get version. don't you just love this ugly stuff
VERSION=`grep "^maxview" debian/changelog |head -1 | awk -F "[()]" '{print $2}'`
echo Version $VERSION

# or maybe you would prefer this? I think it is worse
#grep "^maxview" debian/changelog |head -1 | sed "s/.*(\(.*\)).*/\\1/"

for chrootdir in $DISTLIST
do

    #rm -f ../maxview_*
    #sudo cowbuilder --update --basepath $chrootdir
    DIST=$(basename $chrootdir | cut -d'-' -f2)
    ARCH=$(basename $chrootdir | cut -d'-' -f3)
    ARCH=${ARCH%.cow}
    #[ -d $RESULTDIR/$DIST ] || mkdir $RESULTDIR/$DIST
    #DIST=$DIST pdebuild --pbuilder cowbuilder\
    #                    --buildresult $RESULTDIR/$DIST\
    #                    -- --basepath $chrootdir
    echo $DIST $ARCH
    RESULT=$RESULTDIR/$DIST
    mkdir -p $RESULT
    chmod 777 $RESULT

    # we are now using cowbuilder but it seems incompatible with 
    # git-buildpackage, so use git-pbuilder instead for now :-(
    DIST=$DIST ARCH=$ARCH scripts/git-pbuilder-maxview $RESULT > $LOGDIR/$DIST-$ARCH.log
    if [ $? -ne 0 ]; then
	echo "- error"
    else
	#rename "s#\$$RESULT/(.*).deb#${RESULT}/\$1_${DIST}.deb#" $RESULT/*.deb
	DEB=$RESULT/maxview_${VERSION}_$ARCH.deb
	sudo chmod a+r $DEB
	#ls -l $DEB

	# copy into the 'all' directory with a _dist filename
	cp $DEB $ALLDIR/maxview_${VERSION}_${ARCH}_$DIST.deb
    fi
    echo

    # generates
    # -rw-rw-r--  1 sglass sglass       898 2010-11-03 20:51 maxview_0.7-1.diff.gz
    #-rw-r--r--  1 sglass sglass       848 2010-11-03 20:51 maxview_0.7-1.dsc
    #-rw-------  1 nobody nogroup     1464 2010-11-03 20:56 maxview_0.7-1_i386.changes
    #-rw-------  1 nobody nogroup  1159314 2010-11-03 20:56 maxview_0.7-1_i386.deb
    #sudo chmod 664 $OUT
    #mv -f $OUT $RESULTDIR/$DIST/
done


#git-buildpackage
#git-pbuilder             <---
#calls pbuilder


#DIST=jaunty ARCH=i386 git-pbuilder -- --buildresult ../release.latest/jaunty
#ARCH=i386 git-buildpackage --git-dist=karmic

# we have to do hardy manually as it is on a 'hardy' branch
# should figure this out...
#DIST=hardy pdebuild --pbuilder cowbuilder --buildresult ../release/hardy/ --debbuildopts "-i'(?:^|/)\\.git(attributes)?(?:\$|/.*\$)' -I.git $*" -- --basepath /var/cache/pbuilder/base-hardy-i386.cow/
