#!/bin/bash

dest=../paperman_1.1.orig.tar.bz2

exclude=".git"
# .moc .ui .obj Makefile debian/changelog doc/ tests

for item in ${exclude}; do
   excludes+="--exclude ${item} "
done

# Make a tar file excluding the compiled files
tar cfj $dest ${excludes} .
